# Generated by Django 6.0.2 on 2026-02-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('description', models.TextField(db_column='description')),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
