# Generated by Django 6.0.2 on 2026-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_client_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(db_column='cpf', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(db_column='rg', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registragion',
            field=models.CharField(db_column='registration', max_length=50, unique=True),
        ),
    ]
