# Generated by Django 6.0.2 on 2026-02-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_client_cpf_alter_client_rg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nrf', models.CharField(db_column='nrf', max_length=50, unique=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.client')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.employee')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.product')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
